parameters:
  - name: stageName
    type: string
  - name: displayName
    type: string
  - name: agentPool
    type: string
  - name: variableGroup
    type: string
  - name: databricksTarget
    type: string

jobs:
  - job: DeployJob
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: 0
    pool: ${{ parameters.agentPool }}
    variables:
      - group: ${{ parameters.variableGroup }}
      - name: FULL_REFRESH
        value: false
    steps:
      - script: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          ls -l $HOME/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          echo "Checking uv version..."
          uv --version
        displayName: "Install uv"

      - script: |
          echo "Removing old Databricks CLI binary (if any)..."
          rm /usr/local/bin/databricks
          echo "Downloading Databricks CLI and installing it"
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          echo "Checking Databricks CLI version..."
          databricks version
        displayName: "Install Databricks CLI"

      - script: |
          envsubst < ./.azuredevops/.azure-pipelines/databricks.cfg > ~/.databrickscfg
        env:
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
          AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        displayName: "Configure Databricks authentication"

      - script: |
          export PATH="$HOME/.local/bin:$PATH"
          databricks bundle deploy -t ${{ parameters.databricksTarget }} --auto-approve
        displayName: "Deploy to ${{ parameters.displayName }}"
