# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

from databricks.sdk.runtime import display, spark

# COMMAND ----------

# MAGIC %md
# MAGIC #### Explore the Bronze Table
# MAGIC The `table_location` corresponds with the `autoloader_path` parameter.

# COMMAND ----------

table_location = "dbfs:/databricks-datasets/nyctaxi-with-zipcodes/subsampled"

df = spark.read.format("delta").load(table_location)
display(df)
