name: Deploy Databricks Asset Bundle

# trigger:
#   branches:
#     include:
#       - main
#       - release/*

trigger: none

stages:
  - stage: Development
    jobs:
      - template: templates/deploy-dab-template.yml
        parameters:
          stageName: "Development"
          displayName: "Deploy to Development"
          agentPool: "sup-dp"
          variableGroup: "sup-dev"
          databricksTarget: "dev"

  - stage: Acceptance
    dependsOn: Development
    jobs:
      - template: templates/deploy-dab-template.yml
        parameters:
          stageName: "Acceptance"
          displayName: "Deploy to Acceptance"
          agentPool: "sup-dp"
          variableGroup: "sup-acc"
          databricksTarget: "acc"

  - stage: wait_for_approval
    displayName: Manual validation
    dependsOn: Acceptance
    jobs:
      - job: manual_validation
        displayName: Manual validation
        pool: server
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 720 # 12 hours
            inputs:
              instructions: "Please approve promotion to **production**."
              notifyUsers: |
                someone@superunie.nl
                another@superunie.nl

  - stage: Production
    dependsOn: wait_for_approval
    jobs:
      - template: templates/deploy-dab-template.yml
        parameters:
          stageName: "Production"
          displayName: "Deploy to Production"
          agentPool: "sup-dp"
          variableGroup: "sup-prod"
          databricksTarget: "prod"
