trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Checkout the repository and fetch all history and tags
  - checkout: self
    persistCredentials: true   # Ensures the OAuth token is stored for Git operations
    ref: 'main'                # Ensure you're on the main branch
    clean: true
    fetchDepth: 0
    displayName: 'Checkout repository'

  # 2. Configure Git (so that Semantic Release’s git plugin can commit changes)
  - script: |
      git config --global user.name "Semantic Release Bot"
      git config --global user.email "semantic-release[bot]@azure.com"
    displayName: 'Configure Git'

  # 3. Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # 4. Install Semantic Release and required plugins
  - script: |
      npm install --no-save \
        semantic-release \
        @semantic-release/changelog \
        @semantic-release/exec \
        @semantic-release/git
    displayName: 'Install Semantic Release'

  # 5. Run Semantic Release
  - script: npx semantic-release
    displayName: 'Run Semantic Release'
    env:
      # Pass the Azure DevOps OAuth token so that Git push operations are authenticated.
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
