repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.4.0post1
    hooks:
      - id: pre-commit-update
        args:
          - --verbose
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
          - --fix
          - --exit-non-zero-on-fix
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        args:
          - --config=pyproject.toml
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - --strict
          - --allow-untyped-decorators
          - --ignore-missing-imports
          - --disable-error-code=name-defined
        additional_dependencies:
          - types-pytz
        exclude: scratch
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.5.7
    hooks:
      - id: pydoclint
        args:
          - --config=pyproject.toml
  - repo: local
    hooks:
      - id: pytest-unit-tests
        name: pytest-unit-tests
        entry: >
          bash -c '
            poetry run pytest -v tests --cov=src &&
            poetry run coverage-badge -f -o docs/assets/coverage.svg
          '
        language: system
        pass_filenames: false
        stages: [commit]
