repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages:
        -   pre-push
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.2
    hooks:
    -   id: uv-lock
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
-   repo: local
    hooks:
    -   id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi, jupyter]
    -   id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi, jupyter]
    -   id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        exclude: "scratch"
    -   id: pydoclint
        name: pydoclint
        entry: uv run pydoclint
        language: system
        types: [python]
