# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

from databricks.sdk.runtime import display, spark

# COMMAND ----------

# MAGIC %md
# MAGIC #### List all tables in the current schema
# MAGIC Ensure you have selected the correct catalog and schema in the top right corner.

# COMMAND ----------

display(spark.sql("SHOW TABLES"))

# COMMAND ----------

# MAGIC %md
# MAGIC #### Explore the Bronze Table
# MAGIC Replace `bronze_nyctaxi` with your actual table name if different.

# COMMAND ----------

table_name = "bronze_nyctaxi"

if spark.catalog.tableExists(table_name):
    df = spark.read.table(table_name)
    display(df)
else:
    print(f"Table {table_name} not found. Please check your schema.")
