name: Deploy Databricks Bundle
description: >
  Composite action that installs the Databricks CLI, uv, authenticates
  against Databricks, and deploys the bundle to the requested target.

inputs:
  target:
    description: Bundle target (test | prod)
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Databricks CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
        databricks version

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version

    - name: Authenticate Databricks
      shell: bash
      run: |
        cat > ~/.databrickscfg << EOF
        [DEFAULT]
        host = $DATABRICKS_HOST
        client_id = $DATABRICKS_CLIENT_ID
        client_secret = $DATABRICKS_CLIENT_SECRET
        EOF
        chmod 600 ~/.databrickscfg

    - name: Deploy Databricks bundle
      shell: bash
      run: databricks bundle deploy --target "${{ inputs.target }}"
