name: Deploy Databricks Bundle
description: >
  Composite action that installs the Databricks CLI, uv, authenticates
  against Databricks, and deploys the bundle to the requested target.

inputs:
  target:
    description: Bundle target (test | prod)
    required: true
  databricks_host:
    description: Databricks host URL
    required: true
  databricks_client_id:
    description: Databricks client ID
    required: true
  databricks_client_secret:
    description: Databricks client secret
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Databricks CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
        databricks version

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version

    - name: Deploy Databricks bundle
      shell: bash
      run: databricks bundle deploy --target "${{ inputs.target }}"
      env:
        DATABRICKS_HOST: ${{ inputs.databricks_host }}
        DATABRICKS_CLIENT_ID: ${{ inputs.databricks_client_id }}
        DATABRICKS_CLIENT_SECRET: ${{ inputs.databricks_client_secret }}