services:
  databricks_container:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: databricksruntime-development-container:latest
    volumes:
      # Mount the workspace directory
      - ../:/workspace:cached
      # Mount the local SSH directory
      - ${HOME}/.ssh:/root/.ssh:ro
      # - ${USERPROFILE}/.ssh:/root/.ssh:ro  # Windows
      # Mount the local Databricks configuration file
      - ${HOME}/.databrickscfg:/root/.databrickscfg:ro
      # - ${USERPROFILE}/.databrickscfg:/root/.databrickscfg:ro  # Windows
