name: Deploy Databricks Asset Bundle

# Before using this workflow, create the following in your GitHub repository:
# 1. Go to Settings → Environments
# 2. Create environments: 'test' and 'prod'
# 3. For 'prod' environment add required reviewers under Protection rules
# 4. Ensure the following environment-specific secrets are set:
#    - DATABRICKS_HOST
#    - DATABRICKS_CLIENT_ID
#    - DATABRICKS_CLIENT_SECRET

on:
  workflow_run:
    workflows:
      - Semantic Release
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy_test:
    name: Deploy to test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to test
        uses: ./.github/actions/cd
        with:
          target: test
          databricks_host: ${{ "{{" }} secrets.DATABRICKS_HOST {{ "}}" }}
          databricks_client_id: ${{ "{{" }} secrets.DATABRICKS_CLIENT_ID {{ "}}" }}
          databricks_client_secret: ${{ "{{" }} secrets.DATABRICKS_CLIENT_SECRET {{ "}}" }}

  deploy_prod:
    name: Deploy to production
    needs: deploy_test
    runs-on: ubuntu-latest
    environment: prod
    if: needs.deploy_test.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to production
        uses: ./.github/actions/cd
        with:
          target: prod
          databricks_host: ${{ "{{" }} secrets.DATABRICKS_HOST {{ "}}" }}
          databricks_client_id: ${{ "{{" }} secrets.DATABRICKS_CLIENT_ID {{ "}}" }}
          databricks_client_secret: ${{ "{{" }} secrets.DATABRICKS_CLIENT_SECRET {{ "}}" }}
