name: Deploy Databricks Asset Bundle

# Before using this workflow, create the following in your GitHub repository:
# 1. Go to Settings → Environments
# 2. Create environments: 'test' and 'prod'
# 3. For 'prod' environment add required reviewers under Protection rules
# 4. Ensure the following environment-specific secrets are set:
#    - DATABRICKS_HOST
#    - DATABRICKS_CLIENT_ID
#    - DATABRICKS_CLIENT_SECRET

on:
  push:
    tags:
      - '*'

jobs:
  deploy_test:
    name: Deploy to test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to test
        uses: ./.github/actions/cd
        with:
          target: test
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

  wait_for_approval:
    name: Await production approval
    needs: deploy_test
    runs-on: ubuntu-latest
    timeout-minutes: 720 # 12 hours
    steps:
      - name: Wait for approval
        run: |
          echo "Production deployment for ${{ github.ref_name }} has been approved and will proceed"

  deploy_prod:
    name: Deploy to production
    needs: wait_for_approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to production
        uses: ./.github/actions/cd
        with:
          target: prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
