name: Deploy Databricks Asset Bundle

on:
  push:
    branches: [ main, release/** ]

jobs:
# ────────────────  TEST  ────────────────
  deploy_test:
    name: Deploy to test
    if: startsWith(github.ref, 'refs/heads/main/')
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-dab
        with:
          target: test
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

# ───────  MANUAL APPROVAL (prod env gate)  ───────
  wait_for_approval:
    name: Await production approval
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: deploy_test
    runs-on: ubuntu-latest
    environment: prod          # ← triggers the approval gate
    steps:
      - run: echo "Pausing — please approve to continue to production…"

# ────────────────  PROD  ────────────────
  deploy_prod:
    name: Deploy to production
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: wait_for_approval
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-dab
        with:
          target: prd
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
