name: Deploy Databricks Asset Bundle

on:
  push:
    branches:
      - main
      - release/**

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
          databricks version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv --version

      - name: Authenticate Databricks
        run: |
          cat > ~/.databrickscfg << EOF
          [DEFAULT]
          host = $DATABRICKS_HOST
          client_id = $DATABRICKS_CLIENT_ID
          client_secret = $DATABRICKS_CLIENT_SECRET
          EOF
          chmod 600 ~/.databrickscfg
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS-HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS-CLIENT-ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS-CLIENT-SECRET }}

      - name: Deploy Databricks Bundle
        run: |
          databricks bundle deploy --target dev
