name: CI DABs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ci-dabs:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          # Default configurations
          - os: ubuntu-latest
            cicd_provider: github
            cloud_provider: azure
            include_example_jobs: yes
            support_windows: no
          - os: macos-latest
            cicd_provider: github
            cloud_provider: azure
            include_example_jobs: yes
            support_windows: no
          - os: windows-latest
            cicd_provider: github
            cloud_provider: azure
            include_example_jobs: yes
            support_windows: yes
          # Non-default configuration
          - os: ubuntu-latest
            cicd_provider: azure
            cloud_provider: aws
            include_example_jobs: no
            support_windows: no
          - os: macos-latest
            cicd_provider: azure
            cloud_provider: aws
            include_example_jobs: no
            support_windows: no
          - os: windows-latest
            cicd_provider: azure
            cloud_provider: aws
            include_example_jobs: no
            support_windows: yes

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Install Databricks CLI
        uses: databricks/setup-cli@v1.7.0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          ignore-empty-workdir: true
          enable-cache: false

      - name: Install Just
        uses: extractions/setup-just@v4

      - name: Create init parameters JSON
        run: |
          echo '{
            "project_name": "revo-dabs-test-project",
            "project_description": "This project is generated using our own RevoData Declarative Automation Bundle Templates.",
            "author": "Thomas Brouwer",
            "email": "thomas.brouwer@revodata.nl",
            "setup_type": "tailored",
            "include_cicd": "yes",
            "cicd_provider": "${{ matrix.cicd_provider }}",
            "cloud_provider": "${{ matrix.cloud_provider }}",
            "include_example_jobs": "${{ matrix.include_example_jobs }}",
            "support_windows": "${{ matrix.support_windows }}"
          }' > init_params.json

      - name: Initialize Declarative Automation Bundle from template
        run: |
          echo "Using branch: $BRANCH_NAME"
          databricks bundle init https://github.com/revodatanl/revo-dabs --branch $BRANCH_NAME --config-file init_params.json
        shell: bash
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      - name: Run PowerShell script
        if: matrix.os == 'windows-latest'
        run: |
          cd revo-dabs-test-project
          pwsh -NoProfile -ExecutionPolicy Bypass -File "./.just/just_bash.ps1"
          cd ..

      - name: Build and test Declarative Automation Bundle with justfile
        run: |
          cd revo-dabs-test-project
          echo ""
          echo "=================================================================="
          echo "=============== BUILD PROJECT (WITH DEFAULT TARGET) =============="
          echo "=================================================================="
          just

          echo ""
          echo "=================================================================="
          echo "=============== RE-BUILD PROJECT (WITH SETUP TARGET) ============="
          echo "=================================================================="
          just setup

          echo ""
          echo "=================================================================="
          echo "==================== COMMIT ALL FILES ============================"
          echo "=================================================================="
          uv run prek autoupdate || true
          git config --global user.email "pipeline@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "feat: initial commit"

          echo ""
          echo "=================================================================="
          echo "======================== LINT PROJECT ============================"
          echo "=================================================================="
          just lint

          echo ""
          echo "=================================================================="
          echo "========================= RUN TESTS =============================="
          echo "=================================================================="
          just test


          echo ""
          echo "=================================================================="
          echo "======================== CLEAN PROJECT ==========================="
          echo "=================================================================="
          just clean

          echo ""
          echo "=================================================================="
          echo "================ RE-BUILD PROJECT (AFTER CLEAN) =================="
          echo "=================================================================="
          just

          echo ""
          echo "=================================================================="
          echo "======================== VALIDATE BUNDLE ========================="
          echo "=================================================================="
          databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
